spring:
    application:
        name: spring-gift
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:test

jwt:
    secret: fe1a340e3813faa8630be358ce1ab6cc13a65f4ff0ee7ecb28101130437ccefc
    expiration: 86400000
